"""Pydantic schemas for the public API surface."""

from api.schemas.common import DataSource, ErrorResponse
from api.schemas.location import (
    AreaInfo,
    Coordinates,
    DisasterEvent,
    DisasterHistory,
    DisastersResponse,
    ElevationResponse,
    FloodInfo,
    FloodRiskResponse,
    HazardIndex,
    HazardReading,
    HazardsResponse,
    LocationInfo,
    NearbyPlace,
    NearbyPlaces,
    PlaceCategory,
    PlacesResponse,
    SearchResponse,
    SearchResult,
    TerrainInfo,
    WaterFeature,
)
from api.schemas.report import (
    Assessment,
    AssessmentFactor,
    HealthResponse,
    LocationReport,
    ReportMeta,
)

__all__ = [
    "AreaInfo",
    "Assessment",
    "AssessmentFactor",
    "Coordinates",
    "DataSource",
    "DisasterEvent",
    "DisasterHistory",
    "DisastersResponse",
    "ElevationResponse",
    "ErrorResponse",
    "FloodInfo",
    "FloodRiskResponse",
    "HazardIndex",
    "HazardReading",
    "HazardsResponse",
    "HealthResponse",
    "LocationInfo",
    "LocationReport",
    "NearbyPlace",
    "NearbyPlaces",
    "PlaceCategory",
    "PlacesResponse",
    "ReportMeta",
    "SearchResponse",
    "SearchResult",
    "TerrainInfo",
    "WaterFeature",
]
